---
- name: Set up the Nodesource RPM directory.
  set_fact:
    nodejs_rhel_rpm_dir: "pub_{{ nodejs_version }}"

- name: Import Nodesource RPM key (CentOS < 7).
  rpm_key:
    key: http://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version | int < 7

- name: Import Nodesource RPM key (CentOS 7+).
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  when: ansible_distribution_major_version | int >= 7

- name: Add Nodesource repositories for Node.js (CentOS < 7).
  yum:
    name: "http://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version | int < 7
  register: node_repo

  
- name: Update mirror lists
  command: cd /etc/yum.repos.d/
  when: ansible_distribution_major_version | int >= 7

- name: Update Mirror Lists 2
  command: sudo sed -i '/etc/yum.repos.d/s/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
  when: ansible_distribution_major_version | int >= 7

- name: Update Mirror Lists 3
  command: sudo sed -i '/etc/yum.repos.d/s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
  when: ansible_distribution_major_version | int >= 7
  
- name: Add Nodesource repositories for Node.js (CentOS 7+).
  yum:
    name: "https://rpm.nodesource.com/{{ nodejs_rhel_rpm_dir }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present
  when: ansible_distribution_major_version | int >= 7
  register: node_repo



- name: Update package cache if repo was added.
  yum: update_cache=yes
  when: node_repo is changed
  tags: ['skip_ansible_lint']


- name: Ensure Node.js and npm are installed.
  yum:
    name: "nodejs-{{ nodejs_version | regex_replace('x', '') }}*"
    state: present
    enablerepo: nodesource
